# Generated by Django 5.2 on 2025-08-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wishlist_unique_together_alter_review_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
